DROP TABLE order_packages;
DROP TABLE trip_destination;
DROP TABLE trip_package;
DROP TABLE travel_order;
DROP TABLE payroll_log;
DROP TABLE attendance;
DROP TABLE speaks;
DROP TABLE manager;
DROP TABLE broker;
DROP TABLE agent;
DROP TABLE employee;
DROP TABLE customer;
DROP TABLE language;
DROP TABLE trip_status;
DROP TABLE destination;
DROP TABLE trip_type;
DROP TABLE salary_rate;
DROP TABLE address;

